### ISSUE TITLE
Add link to Code of Conduct to the web site

### ISSUE THREAD

**Issue by mkchandler** [codeforokc/codeforokc#1]
Link could be in the footer and should point to: https://github.com/codeforokc/codeofconduct

**Comment by amandaharlin** [comment]
are you keeping the theme code inside this repo? if so, then i'll make a pull request with the change added it

**Comment by amandaharlin** [comment]
what footer style do you prefer? jw

![screen shot 2014-12-31 at 7 14 40 pm](https://cloud.githubusercontent.com/assets/716644/5591447/5a0908d8-9121-11e4-97a3-ca63b9b9a48e.png)

![screen shot 2014-12-31 at 7 16 35 pm](https://cloud.githubusercontent.com/assets/716644/5591450/8ef96dc6-9121-11e4-80e9-d82c0d217264.png)

**Comment by jagthedrummer** [comment]
I like the horizontal one. :)

**Comment by amandaharlin** [comment]
hehehe +1

**Comment by mkchandler** [comment]
I've deployed this change, thanks for making it!
