### ISSUE TITLE
Add an About page

### ISSUE THREAD

**Issue by mkchandler** [codeforokc/codeforokc#2]
Need to add an "About" page to the web site. It should at least include:

* Summary of the group and what we do
* List of core team members and what each do

**Comment by amandaharlin** [comment]
can i get a list of the people & their roles? i only know 3 people so far, which might be all there is rn.

**Comment by mkchandler** [comment]
Matt Chandler - Captain
Catherine Lippert - Storyteller
Jeremy Green - Delivery Lead

There are descriptions of these roles here: https://docs.google.com/document/d/1oEB1CuzCHldxP_bzcvmcrmK0yAE1BzV2AGhtwtYKZVY/edit

We are working on an "official" long description of the group and what we do. When we get that finalized (soon), we can add it to the "About" page.
