### ISSUE TITLE
Other pages to add?

### ISSUE THREAD

**Issue by amandaharlin** [codeforokc/codeforokc#5]
In the config.yml i saw other not-yet-implemented menu items, like:

  #Meetings: /meetings
  #Forum: https://github.com/codeforokc/discussions/issues
  #Chat: https://gitter.im/codeforokc/discussions
  #Join Us: /join-us
  #Archives: /archives

do you want to add these in still?

**Comment by jagthedrummer** [comment]
Nah, I just consolidated all of that info onto the home page. I should have just deleted that stuff as I was cleaning up.

**Comment by amandaharlin** [comment]
ok awesome :)
